### ISSUE TITLE
Collapsing doesn't seem to work

### ISSUE THREAD

**Issue by damouse** [mukeshsoni/deepnotes-editor#1]
It looks like collapsing items works on deepnotes.in, but not running locally on deepnotes-editor. It worked for me on `v0.1.1-0`, but not on master. Any chance this is an easy fix? 

Thanks for your work on the clone!

**Comment by mukeshsoni** [comment]
@damouse Thanks for the bug report. Have fixed the bug in version `0.1.6` and also in master branch.
